# Generated by Django 2.2.5 on 2019-09-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('care_type', models.CharField(max_length=100)),
                ('id_num', models.IntegerField(blank=True)),
                ('cacpacity', models.IntegerField(blank=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('in_business', models.BooleanField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True)),
                ('accs', models.BooleanField(blank=True, null=True)),
                ('erc', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
