# Generated by Django 2.2.5 on 2019-09-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterField(
            model_name='facility',
            name='care_type',
            field=models.CharField(choices=[('RCF', 'Residential Care Facility'), ('ALR', 'Assisted Living Residence')], max_length=100),
        ),
    ]
