# Generated by Django 2.2.5 on 2019-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0002_auto_20190918_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='accs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='erc',
            field=models.BooleanField(default=False),
        ),
    ]
