# Generated by Django 2.2.5 on 2019-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0004_remove_facility_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id_num',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
