# Generated by Django 2.2.5 on 2019-09-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0005_auto_20190918_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
