# Generated by Django 2.2.5 on 2019-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0007_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
