# Generated by Django 2.2.5 on 2019-09-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0008_inspection_inspection_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='cacpacity',
            new_name='capacity',
        ),
    ]
