# Generated by Django 2.2.5 on 2019-09-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0009_auto_20190919_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('received_start_date', models.DateField()),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.Facility')),
                ('related_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.Inspection')),
            ],
        ),
    ]
