# Generated by Django 2.2.5 on 2019-09-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0011_allegation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allegation',
            name='complaint',
        ),
        migrations.AddField(
            model_name='complaint',
            name='allegations',
            field=models.ManyToManyField(to='eldercare.Allegation'),
        ),
    ]
