# Generated by Django 2.2.5 on 2019-09-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0012_auto_20190919_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='allegations',
        ),
        migrations.AddField(
            model_name='allegation',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.Complaint'),
        ),
    ]
