# Generated by Django 2.2.5 on 2019-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0016_auto_20190919_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegation',
            name='finding',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='allegation',
            name='substantiation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
