# Generated by Django 2.2.5 on 2019-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0017_auto_20190924_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penalties',
            new_name='Penalty',
        ),
        migrations.AlterField(
            model_name='facility',
            name='care_type',
            field=models.CharField(max_length=100),
        ),
    ]
