# Generated by Django 2.2.5 on 2019-09-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0018_auto_20190926_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name_plural': 'penalties'},
        ),
    ]
