# Generated by Django 2.2.6 on 2019-10-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0020_auto_20191011_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_num', models.CharField(blank=True, max_length=20, null=True)),
                ('severity_scope', models.CharField(blank=True, max_length=1, null=True)),
                ('citation_type', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(blank=True, max_length=200, null=True)),
                ('scope', models.CharField(blank=True, max_length=200, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.Facility')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.Inspection')),
            ],
        ),
    ]
