# Generated by Django 2.2.6 on 2019-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0022_auto_20191015_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity_Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('score', models.IntegerField()),
                ('severity', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
            ],
        ),
    ]
