# Generated by Django 2.2.6 on 2019-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0023_severity_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='severity_scope',
            name='scope_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='severity_scope',
            name='severity_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='severity_scope',
            name='scope',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='severity_scope',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='severity_scope',
            name='severity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
