# Generated by Django 2.2.6 on 2019-11-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0025_auto_20191101_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='slug',
        ),
    ]
