# Generated by Django 2.2.6 on 2019-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0026_remove_inspection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=300),
        ),
    ]
