# Generated by Django 2.2.6 on 2019-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0027_inspection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
