# Generated by Django 2.2.6 on 2019-11-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0028_facility_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='related_inspection',
        ),
    ]
