# Generated by Django 2.2.6 on 2019-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0029_remove_complaint_related_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='closedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='opendate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
