# Generated by Django 2.2.6 on 2019-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0030_auto_20191115_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='formername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
