# Generated by Django 2.2.7 on 2019-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare', '0032_facility_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='under_appeal',
            field=models.BooleanField(default=False),
        ),
    ]
